Added NEFFEX/Fight Back: The Collection/Fight Back
Lyrics/lyrics pull request #725
Opened 2022-02-09 07:47 UTC by TheBinaryLoop

2022-02-09 08:14 UTC, snshn requested changes
The name of the album contains a colon, the cloning of this repo may fail on Windows... let's run the workflow and see if it works or not

2022-02-09 08:14 UTC, snshn commented on database/N/NEFFEX/Fight Back: The Collection/Fight Back
> +Original text by  Brandon Horth/Cameron Wales
Could you please write authors of the original text as: `Brandon Horth / Cameron Wales` or `Brandon Horth,  Cameron Wales` (whichever you think fits better)?

2022-02-09 08:14 UTC, snshn commented on database/N/NEFFEX/Fight Back: The Collection/Fight Back
> +Language          American English
I usually put Language below Year, easier to read metadata for humans that way.

2022-02-09 08:14 UTC, snshn commented on database/N/NEFFEX/Fight Back: The Collection/Fight Back
> +You're never gonna make it, you're not good enough
Could you please change the `'` signs to proper apostrophe signs?  More info here: https://smartquotesforsmartpeople.com

2022-02-09 08:17 UTC, snshn commented
Yeah, Windows CI fails because of that colon... the conventional way to deal about that type of names is usually to rename to something more filesystem-friendly, e.g. `Fight Back - The Collection`, but the name in the metadata of course can stay the same, and that's how it's going to be displayed in HTML on the website, with colon.

2022-02-09 08:24 UTC, TheBinaryLoop commented
Changes were made as requested

2022-02-10 03:07 UTC, snshn approved these changes

2022-02-10 03:09 UTC, snshn commented
Hey, thank you for this contribution Lukas!

2022-02-10 03:09 UTC, merged